"""List commands for Claude Agent SDK CLI.

Contains commands for listing skills, agents, and sessions.
Uses a factory pattern to reduce code duplication.
"""
import asyncio
import os
from collections.abc import Awaitable, Callable

from agent.display import print_error
from cli.clients import APIClient
from cli.commands.handlers import show_skills, show_agents, show_subagents, show_sessions


def _create_list_command(
    name: str,
    show_func: Callable[[Callable[[], Awaitable[list[dict]]]], Awaitable[None]],
    list_method_name: str,
    description: str
) -> Callable[[], None]:
    """Factory for creating list commands.

    Creates a command function that fetches data from the API and displays it
    using the provided show function.

    Args:
        name: Human-readable name for error messages (e.g., 'skills', 'agents').
        show_func: Async function that takes a list method and displays results.
        list_method_name: Name of the method on APIClient to call for fetching data.
        description: Description for the command docstring.

    Returns:
        A command function that can be used as a CLI command.
    """

    def command() -> None:
        """Command function generated by the factory."""

        async def _show() -> None:
            api_key = os.getenv("API_KEY")
            client = APIClient(api_key=api_key)
            try:
                list_method = getattr(client, list_method_name)
                await show_func(list_method)
            finally:
                await client.disconnect()

        try:
            asyncio.run(_show())
        except Exception as e:
            print_error(f"Error listing {name}: {e}")

    # Set the docstring for the command
    command.__doc__ = description
    command.__name__ = f"{name}_command"

    return command


# Create list commands using the factory
skills_command = _create_list_command(
    name="skills",
    show_func=show_skills,
    list_method_name="list_skills",
    description="List available skills.\n\nDisplays all skills discovered from .claude/skills/ directory."
)

agents_command = _create_list_command(
    name="agents",
    show_func=show_agents,
    list_method_name="list_agents",
    description="List available top-level agents.\n\nDisplays all registered agents that can be selected via agent_id."
)

subagents_command = _create_list_command(
    name="subagents",
    show_func=show_subagents,
    list_method_name="list_subagents",
    description="List available subagents.\n\nDisplays all delegation subagents used within conversations."
)

sessions_command = _create_list_command(
    name="sessions",
    show_func=show_sessions,
    list_method_name="list_sessions",
    description="List conversation sessions.\n\nShows session history from storage."
)
