import type { ContentBlock, TextContentBlock, ImageContentBlock } from '@/types';

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

export function validateMessageContent(content: string | ContentBlock[]): ValidationResult {
  if (typeof content === 'string') {
    if (!content.trim()) {
      return { valid: false, error: 'Message content cannot be empty' };
    }
    return { valid: true };
  }

  if (!Array.isArray(content) || content.length === 0) {
    return { valid: false, error: 'Content blocks must be a non-empty array' };
  }

  for (let i = 0; i < content.length; i++) {
    const block = content[i] as ContentBlock;

    if (!block || typeof block !== 'object') {
      return { valid: false, error: `Content block at index ${i} must be an object` };
    }

    if (!block.type || typeof block.type !== 'string') {
      return { valid: false, error: `Content block at index ${i} must have a valid type` };
    }

    if (block.type === 'text') {
      const textBlock = block as TextContentBlock;
      if (typeof textBlock.text !== 'string') {
        return { valid: false, error: `Text content block at index ${i} must have a text property` };
      }
    } else if (block.type === 'image') {
      const imageBlock = block as ImageContentBlock;
      if (!imageBlock.source || typeof imageBlock.source !== 'object') {
        return { valid: false, error: `Image content block at index ${i} must have a source object` };
      }

      if (!imageBlock.source.type || !['base64', 'url'].includes(imageBlock.source.type)) {
        return { valid: false, error: `Image source type at index ${i} must be either "base64" or "url"` };
      }

      if (imageBlock.source.type === 'base64' && !imageBlock.source.data) {
        return { valid: false, error: `Base64 image at index ${i} must include data property` };
      }

      if (imageBlock.source.type === 'url' && !imageBlock.source.url) {
        return { valid: false, error: `URL image at index ${i} must include url property` };
      }
    } else if (block.type === 'audio' || block.type === 'video' || block.type === 'file') {
      // Audio, video, and file blocks are valid content types (generated by agent)
    } else {
      return { valid: false, error: `Unknown content block type at index ${i}` };
    }
  }

  return { valid: true };
}

export async function compressImage(
  file: File,
  maxSizeBytes: number = 10 * 1024 * 1024,
  maxDimension: number = 2048
): Promise<File> {
  // If file is already small enough, return as-is
  if (file.size <= maxSizeBytes) {
    return file;
  }

  return new Promise((resolve, reject) => {
    const img = new Image();
    const url = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(url);

      // Calculate new dimensions while maintaining aspect ratio
      let { width, height } = img;
      const aspectRatio = width / height;

      if (width > height) {
        if (width > maxDimension) {
          width = maxDimension;
          height = Math.round(width / aspectRatio);
        }
      } else {
        if (height > maxDimension) {
          height = maxDimension;
          width = Math.round(height * aspectRatio);
        }
      }

      // Create canvas and resize
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;

      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get canvas context'));
        return;
      }

      // Draw resized image
      ctx.drawImage(img, 0, 0, width, height);

      // Try different quality levels until we fit under the size limit
      let quality = 0.92;
      const minQuality = 0.1;
      const qualityStep = 0.05;

      const tryCompress = () => {
        canvas.toBlob(
          (blob) => {
            if (!blob) {
              reject(new Error('Failed to compress image'));
              return;
            }

            // If size is acceptable or quality is too low, use this result
            if (blob.size <= maxSizeBytes || quality <= minQuality) {
              // Create new File object with compressed data
              const compressedFile = new File([blob], file.name, {
                type: file.type,
                lastModified: Date.now(),
              });
              resolve(compressedFile);
            } else {
              // Reduce quality and try again
              quality = Math.max(minQuality, quality - qualityStep);
              tryCompress();
            }
          },
          file.type,
          quality
        );
      };

      tryCompress();
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load image'));
    };

    img.src = url;
  });
}

export async function fileToImageBlock(
  file: File,
  maxSizeBytes: number = 10 * 1024 * 1024
): Promise<ImageContentBlock> {
  if (!file.type.startsWith('image/')) {
    throw new Error('File must be an image');
  }

  // Compress image if needed
  const processedFile = await compressImage(file, maxSizeBytes);

  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => {
      const result = reader.result as string;
      // Extract base64 data from data URL (remove prefix like "data:image/png;base64,")
      const base64Data = result.split(',')[1];

      // Create image block with media_type (required by Claude SDK)
      resolve({
        type: 'image',
        source: {
          type: 'base64',
          media_type: processedFile.type,  // e.g., "image/png", "image/jpeg"
          data: base64Data
        }
      });
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsDataURL(processedFile);
  });
}

